<?php

return [
    'title' => 'Every Dependency Is a Loan',
    'excerpt' => "Adding a package takes eight seconds and costs nothing today. The bill arrives later, on someone else's Tuesday, in a currency you did not agree to.",
    'category' => 'technology',
    'pull_quote' => 'You did not depend on eleven lines of code; you depended on a registry that could be persuaded to forget them.',
    'paragraphs' => [
        'In March 2016, builds started failing across a large slice of the JavaScript world because a package that pads a string with leading characters stopped existing. left-pad was eleven lines long. It did the thing you would write in a minute without looking anything up, and its disappearance broke the build for projects that had never heard of it, including tooling used by Babel and React Native. The lesson people took from this was that developers had forgotten how to program. That reading is comfortable and wrong, and it caused the industry to learn almost nothing from an unusually clear demonstration.',
        'What actually happened was a dispute over a name. Azer Koçulu had a package called kik; Kik Interactive claimed the trademark; npm sided with the company and transferred the name. Koçulu, reasonably angry at having a name taken from him by a registry he had published to in good faith, unpublished more than two hundred of his modules, left-pad among them. It was a transitive dependency several layers down from packages that millions of installs depended on, so the removal propagated instantly. npm eventually took the unprecedented step of restoring the package against the author\'s wishes, and afterwards changed its unpublish policy so this could not recur in the same shape. You did not depend on eleven lines of code; you depended on a registry that could be persuaded to forget them.',
        'That distinction is the whole subject. When you add a package you are not acquiring a file. You are entering an ongoing relationship with a distribution system, a version resolver, and one or more people whose circumstances you know nothing about and whose future behaviour you are quietly assuming. The code is the smallest part of what you took on. The direct dependencies at least got chosen by somebody. The transitive ones arrived as a consequence of that choice, and there are usually far more of them, selected by strangers according to their own judgement about what was worth trusting.',
        'The 2018 event-stream incident showed what that trust actually looks like when someone leans on it. Dominic Tarr had written a popular stream utility years earlier and no longer used it himself. Someone who had been contributing volunteered to take over maintenance, and Tarr, like many maintainers of long-lived packages that are no longer part of their working life, handed it over. The new maintainer added a dependency called flatmap-stream, and a later release of that dependency carried an obfuscated payload. It was encrypted, and the key was derived from the description field of the package it was targeting, so it stayed inert for essentially everyone and decrypted only inside builds of the Copay bitcoin wallet, where it went after wallet credentials. It surfaced when a user noticed something that did not add up and filed an issue about it.',
        "Tarr's response afterwards was the most useful thing said about the whole episode. He had published the code for free, he no longer used it, and he had never agreed to maintain it in perpetuity for people who had never contacted him. Every part of that is correct, and it exposes the actual defect. Maintainership had transferred, which is to say the trust the entire ecosystem had placed in one person silently moved to a different person, and nothing in npm, in semver, in a lockfile, or in any tool in the standard pipeline registered that this had occurred. The package name did not change. The signal did not exist.",
        'The xz backdoor found in March 2024 was the same manoeuvre executed with patience and real skill. An account operating under the name Jia Tan spent about two years contributing genuinely useful work to xz, accompanied by pressure from other accounts on the exhausted original maintainer to hand over more responsibility, until they had commit rights and release authority. The malicious code was not in the git tree. It was assembled during the build from files that only appeared in the release tarballs, and it targeted sshd on distributions where systemd\'s dependency on liblzma pulled the library into the SSH daemon\'s address space. It was caught because Andres Freund, benchmarking Postgres, noticed sshd was burning unexpected CPU and that logins had picked up a small amount of extra latency, and pulled the thread rather than shrugging. A near-universal remote code execution backdoor in the Linux ecosystem was averted by one person being irritated by half a second.',
        'It is worth being precise about what those two incidents have in common, because it is not the code. In both cases the source you would have reviewed at adoption time was fine. The compromise came later, through the human channel, and arrived through an automatic version bump into builds run by people who had made no decision at all that week. Auditing a dependency once, at the moment you add it, protects you against exactly one of the ways it can hurt you.',
        'There is a mechanical hazard sitting alongside the social one, and it is under-appreciated. Package managers run code at install time. npm has lifecycle scripts, Python packages can execute arbitrary code during installation, Ruby gems compile native extensions. This code runs on developer laptops with SSH keys and cloud credentials in the environment, and on CI runners that hold deployment tokens by design. A dependency does not need your application to ever call it. It gets to run before your program does, in a context that is frequently more privileged than production.',
        'Set malice aside entirely and the costs still accumulate, just more quietly. The package ages. It breaks against a new runtime version, or its own dependencies conflict with something else you need. An advisory lands and requires a patch that only exists on a newer major version, which requires an API migration you had not budgeted for, in a quarter where nobody planned for it. Log4Shell in December 2021 was the canonical demonstration of this shape: a remote code execution flaw in a logging library that a very large number of affected organisations had never consciously chosen, because it had arrived underneath a framework. For most of them the expensive part was not applying the patch. It was determining whether they had it at all, and where.',
        'Heartbleed had illustrated the underlying economics seven years earlier. Effectively the entire internet depended on OpenSSL, a project sustained by a tiny group with almost no funding, and a missing bounds check in the TLS heartbeat extension exposed server memory to anyone who asked. The response, the Core Infrastructure Initiative, was an admission of the structural problem: consumption of open source is free, instantaneous and unbounded, while maintenance is unpaid, slow and performed by a finite number of tired people. Nothing in the pipeline that pulls a package into your build communicates anything about that asymmetry.',
        'None of this is an argument for writing everything yourself. That way lies your own TLS implementation, your own timezone database, your own date parser, and a set of bugs that are entirely yours and that nobody else will ever find for you. Mature, widely used dependencies are usually far safer than the code you would write in their place, precisely because so many people have already hit their edges. The argument is narrower: the cost of a dependency is not its size, and asking whether it is only a few kilobytes is measuring the wrong dimension entirely.',
        'The questions that actually predict pain are different ones. How many people can publish a release, and what happens when they lose interest. Does it execute anything at install time. How large is its transitive footprint, and did anyone look at that list. Is the release built from the tag you can read, or from something assembled elsewhere. And the one that clarifies fastest: what would we do, this week, if this package were removed from the registry tomorrow, or if it quietly acquired a new maintainer nobody had heard of.',
        'The practices follow. Copy the eleven-line function rather than importing it. Pin your versions and commit the lockfile. Read lockfile diffs in review with the same attention you give source diffs, because that file is where a change of ownership becomes a change in your software. Prefer the standard library where it is merely adequate. Keep an inventory you can actually query, so that the next time an advisory lands you spend your afternoon patching rather than searching. And treat the dependency count of a service as a number somebody owns, because at the moment it is usually a number that only ever goes up, one eight-second decision at a time.',
    ],
];
