<?php

return [
    'title' => 'Why Software Estimates Fail',
    'excerpt' => 'Estimates are not wrong because engineers are careless. They are wrong because of what an estimate is, structurally, as a claim about the unknown.',
    'category' => 'technology',
    'pull_quote' => 'An estimate is a claim about work you have not yet understood, and the work of understanding it is the work itself.',
    'paragraphs' => [
        'A team says two weeks. It ships in seven. In the retrospective everyone agrees the estimate was bad, which is true and completely useless, because the same team will miss by a similar factor on the next thing, and so will the most disciplined engineering organisation you can name. The failure is not a failure of character. It is a property of the structure of the thing being estimated, and until you look at that structure you will keep prescribing willpower for a problem that does not respond to willpower.',
        "Douglas Hofstadter gave the problem its best joke in Gödel, Escher, Bach: it always takes longer than you expect, even when you take into account Hofstadter's Law. The recursion is the point. Any correction factor you apply becomes part of the system you were correcting for, so the adjusted estimate inherits the same optimism as the original with a larger number in front of it. Doubling your estimates works exactly once. After that, doubling is the baseline you double from, and you are back where you started, only now with a reputation for padding.",
        'Barry Boehm laid out the shape of the problem in Software Engineering Economics, and Steve McConnell later gave it the name that stuck: the cone of uncertainty. At the very beginning of a project, before requirements are settled, an estimate can plausibly land off by a factor of four in either direction. The range narrows as the project proceeds, until at the end it collapses onto the actual duration, at which point it has stopped being an estimate. The part almost everyone gets wrong is the mechanism. The cone does not narrow because time passes; it narrows because uncertainty is resolved. A project that burns three months without settling anything has exactly the spread it started with, and three months less schedule to spend on it.',
        'Then there is the question of what number a person actually gives you when you ask. Almost always it is the mode: the single most likely outcome, the version of the week where the migration script works and the staging environment is up and nobody is out sick. But task durations are not symmetric around that. There is a hard floor, because no amount of luck gets a two-day job done in four hours, and there is no ceiling at all. The long tail is where the undocumented auth service lives. So the honest most-likely answer is systematically below the average outcome, and the person hearing it treats it as a commitment rather than the peak of a lopsided distribution.',
        'You might hope these errors cancel out across a plan of thirty tasks. They do not, for two reasons. The errors are one-sided, because tasks can overrun without limit and can only underrun down to zero. And they are correlated, because the tasks that go wrong tend to go wrong for shared causes: the same ambiguous spec, the same flaky test suite, the same person who turns out to be the only one who understands the billing code. Independent errors would average away. Correlated one-sided errors accumulate.',
        "Fred Brooks worked most of this out in 1975. The Mythical Man-Month is remembered for Brooks's law, that adding people to a late project makes it later, but the argument underneath matters more than the slogan. The man-month is a unit that assumes people and time are interchangeable, which holds only for work that requires no communication between the workers. Real projects require a great deal of it, and communication paths grow roughly as the square of team size, so each new person adds output linearly and adds coordination cost quadratically. Brooks also noticed something more uncomfortable: programmers estimate the part they can picture, which is the coding, and coding is the smallest slice of the schedule. His own rule of thumb gave a third to planning and half to testing and integration, leaving a sixth for the activity everyone imagines when they answer the question.",
        'Eleven years later, in No Silver Bullet, Brooks separated accidental complexity from essential complexity. Accidental complexity is the friction of our tools, and we have been genuinely brilliant at removing it: garbage collection, managed runtimes, package managers, deployment pipelines. Essential complexity is the difficulty of the problem itself, the fact that the invoicing rules really do have forty cases and the third-party API really does return two different shapes for the same status. No tool removes that, and it is precisely the part you cannot see until you are inside it.',
        'Which brings you to the root of the matter. An estimate is a claim about work you have not yet understood, and the work of understanding it is the work itself. The specification is never complete before the build, because building is the process that discovers what the specification actually was. Every unremarkable feature contains a handful of decisions nobody knew were decisions until the code forced the question. Estimating that is not like estimating a drive across a known road. It is like estimating a drive across a road you are also building, in weather you will find out about on the way.',
        'None of this is helped by what organisations do to numbers once they exist. An estimate becomes a plan, a plan becomes a commitment, a commitment becomes a date on a slide that someone outside engineering has now told a customer. The pressure applied to that number is asymmetric: teams are asked to revise estimates downward constantly and upward almost never. And there is a quiet selection effect on top, because the team or vendor that quotes low is the one that wins the work, so the estimates that survive into plans are drawn from the optimistic end of the distribution by construction.',
        'Kahneman and Tversky named the individual version of this the planning fallacy, and their prescription is the most reliable thing in the whole field. Stop reasoning forwards from the plan, which they called the inside view, and reason instead from the outside view: what happened the last twenty times work of this shape was attempted here. People are poor at imagining the specific disaster that will befall them and quite good at remembering that something always does. Your ticket history is a better forecaster than your imagination, and it is sitting right there, unread.',
        'So the practical moves follow from the diagnosis rather than from exhortation. Cut work into pieces small enough that the tail is bounded, because a three-day task can overrun by a week while a three-month task can overrun by a year. Quote ranges rather than points, and let the range be wide enough to be honest, since a narrow range is not confidence but a refusal to state what you do not know. Forecast from throughput you have actually observed instead of from effort you have imagined. Keep the estimate and the commitment as separate artefacts with separate owners. And where a date genuinely cannot move, put the uncertainty into scope, because scope is the only variable in the whole system that is under your control.',
        'The point of all this is not that estimation is impossible or that you should stop trying. Plans are useful; organisations need to make decisions about money and hiring and sequencing, and those decisions require numbers. The point is that a missed estimate is data about the difficulty of the work, not evidence of a moral defect in the people doing it. Treating it as the latter produces the one outcome guaranteed to make forecasts worse: engineers who learn that the safest number is the one that ends the conversation fastest.',
    ],
];
