<?php

return [
    'title' => 'What a Database Index Actually Is',
    'excerpt' => 'A query takes forty seconds. You add one index and it takes three milliseconds. Here is the data structure that makes that happen, and when it will not.',
    'category' => 'technology',
    'pull_quote' => 'An index is not a speed setting; it is a second copy of your data, kept in sorted order, and it helps only when your query names a contiguous stretch of that order.',
    'paragraphs' => [
        'Everyone has had the experience. A query on a table with a few million rows takes forty seconds. You add an index on one column, run it again, and it comes back in three milliseconds. It feels like flipping a switch marked FAST, which is a fine thing to believe right up until the day you add an index and nothing changes, or the planner ignores it, or the query gets faster and every insert gets slower. Underneath there is no switch. There is a specific data structure with a specific shape, and once you can picture the shape, the rules you have been memorising off blog posts become things you can simply derive.',
        'Start with the alternative, because it makes the value obvious. Without an index the table is a heap: rows in pages, in roughly the order they were written, with no ordering you can exploit. To find everyone with a particular email address the database reads every page and tests every row. The cost is proportional to the size of the table, and it stays proportional even when exactly one row matches. That is the whole complaint. You want cost proportional to the size of the answer, and you are paying cost proportional to the size of the haystack.',
        'The obvious fix is to keep the data sorted so you can binary search it, and the obvious problem with that is inserts, since putting a new row in the middle of a sorted array means shifting everything after it. So you reach for a tree, and the textbook binary search tree looks right: logarithmic lookups, cheap insertion. It is still a bad answer, and the reason is that storage is block-addressed. You cannot read eight bytes from disk, and you do not really read eight bytes from memory either. You read a page, typically eight kilobytes in Postgres, or a cache line on the way in from RAM. A binary tree gives you one useful comparison per page you fetch. Twenty levels deep on a million rows means twenty fetches to answer one question, and you have thrown away almost everything each fetch brought you.',
        'The B-tree, published by Rudolf Bayer and Edward McCreight in 1972 out of work at Boeing, is what you get when you take that constraint seriously. Make the node the same size as the page. Now each node holds not one key but hundreds of them, with pointers between them, so a single fetch narrows your search by a factor of several hundred instead of a factor of two. Depth is logarithmic in the branching factor rather than in two, and with a fanout in the hundreds, four levels covers billions of rows. This is the property that matters most in practice and the one that surprises people: the tree gets deeper astonishingly slowly. A table that grows a hundredfold might add one level. Nobody has ever settled what the B stands for, incidentally. Bayer has said balanced, Boeing and Bayer are all plausible readings, and he has never picked one.',
        'What relational databases actually use is the B+tree variant, and its two differences from the textbook B-tree are the ones you feel every day. First, all the actual entries live in the leaf level, and the internal nodes hold nothing but routing keys. Second, the leaves are linked together in sorted order. Those two choices mean a range query costs one descent from the root followed by a sideways walk along the leaves, reading only pages that contain answers. This is why a BETWEEN, an ORDER BY, a greater-than, a LIMIT on sorted output, and a prefix LIKE are all served efficiently by the same structure. They are all the same operation: find a starting point, then walk.',
        'There is a second effect that does most of the real-world work. The upper levels of the tree are tiny relative to the whole and get hit by every single lookup, so they stay in the buffer cache permanently. The root is essentially always resident, the level below it usually is, and often the one below that too. So the nominal four page reads of a lookup are, in practice, three cache hits and one real read. That is the actual gap between forty seconds and three milliseconds. Not clever mathematics. Fewer trips to the disk.',
        'What sits in a leaf entry is the indexed key plus a pointer to the row, and the exact form of that pointer has consequences worth knowing. Postgres stores a physical tuple identifier and keeps the heap separate, so an index scan is a descent followed by a jump into the heap for each matching row. InnoDB does it differently: the table itself is a B+tree keyed on the primary key, so the rows live in the leaves of that tree, and a secondary index stores the primary key value rather than a physical address. A lookup through a secondary index is therefore two descents, one through the secondary index and one through the clustered index. It also means that in MySQL a wide primary key silently inflates every secondary index on the table, which is the real argument against a long composite natural key as a PK.',
        'Now the practical rules stop being folklore. An index is sorted, so it is only useful when your predicate corresponds to a contiguous stretch of that sort order. Everything else follows. A composite index on (tenant_id, created_at) is sorted by tenant first and, within each tenant, by timestamp. Query by tenant, or by tenant and time together, and you are naming a contiguous range. Query by created_at alone and you are not, because those values are scattered across the entire index in as many little runs as there are tenants. That is the leftmost prefix rule, and it is not a rule so much as an observation about what sorted means.',
        'The same observation explains why functions defeat indexes. An index on email is sorted by email, not by lower(email), so a query filtering on lower(email) cannot descend it, because the ordering it needs does not exist in the structure it has. A leading wildcard in LIKE fails for the same reason: you cannot find the start of a range when you do not know how the string begins. So does an implicit type coercion that makes the database compare something other than the stored value. The fix in every case is to make the index store what you actually search on, either with an expression index or with a column that holds the normalised form.',
        "One more corollary is worth having explicitly, because it is the single highest-value rule in day-to-day schema work. In a composite index, put your equality columns first and your range column last. Once the scan opens a range on a column, everything ordered after that column is no longer contiguous, so any further conditions degrade into filtering rows you have already fetched rather than skipping them. An index on (status, created_at) serves a query filtering status = 'active' and created_at > X beautifully. The same index with the columns reversed makes the database walk every row newer than X and throw most of them away.",
        'If the index happens to contain every column the query needs, the database can answer entirely from the index and never touch the table, which is called a covering index or an index-only scan, and it is often the difference between fast and very fast. Postgres lets you add non-key payload columns with INCLUDE for exactly this. It comes with a catch worth knowing about: Postgres keeps row visibility in the heap, so an index-only scan still has to check the visibility map, and on a table that has just been heavily written the pages are not marked all-visible and you go to the heap anyway. A query that gets slower right after a bulk load and faster after a vacuum is usually this.',
        'This is also where you find the answer to why the planner sometimes refuses to use the index you built for it. Reading through an index means one random access per matching row, and random access is expensive; a sequential scan reads pages in order and has no per-row indirection at all. So there is a crossover point, and once a query matches a large enough fraction of the table, scanning everything genuinely is the faster plan. The planner estimates that fraction from collected statistics, which means a planner making a stupid decision is very often a planner working from stale statistics rather than a planner that is wrong.',
        'None of this is free, and the cost lands on writes. Every insert has to add an entry to every index on the table, in the right place, splitting nodes when they fill. Every update to an indexed column is a delete and an insert in that index. Indexes take space, they compete for the same buffer cache as your data, and an index nobody uses is pure overhead paid on every write forever. Which is the whole idea in one line: an index is not a speed setting; it is a second copy of your data, kept in sorted order, and it helps only when your query names a contiguous stretch of that order. Ask that question of your slow query and the answer usually falls out in under a minute.',
    ],
];
