<?php

return [
    'title' => 'Why Fast Computers Feel Slow',
    'excerpt' => 'A 1983 Apple IIe puts a character on screen faster than most machines sold today. The hardware is not the problem, and neither is laziness.',
    'category' => 'technology',
    'pull_quote' => 'The machine is not slow; the distance between the keypress and the pixel got longer, and nobody was assigned to keep it short.',
    'paragraphs' => [
        'Dan Luu once pointed a high-speed camera at a pile of computers spanning forty years and measured how long each one took to get a typed character onto the screen. An Apple IIe from 1983 beat most modern machines. Not most old machines, not most cheap machines: most of what you can buy now, running on processors thousands of times faster with orders of magnitude more memory. That result is not nostalgia and it is not a rhetorical flourish. It is a measurement, and it is the single most useful fact to hold in your head when thinking about why software feels the way it does.',
        'Niklaus Wirth wrote the standard diagnosis in IEEE Computer in February 1995, in an essay called A Plea for Lean Software. Software gets slower faster than hardware gets faster, a formulation he credited to Martin Reiser rather than claiming for himself. The industry has an unofficial version of the same observation: what Andy giveth, Bill taketh away, Grove supplying the transistors and Gates spending them. Both versions are usually deployed as accusations of sloppiness. That is where the analysis normally stops, and it is where it starts going wrong, because the mechanisms involved are mostly not sloppiness at all.',
        'The first mechanism is that computers did not get uniformly faster. They got enormously more throughput and only modestly less latency. David Patterson set this out in Latency Lags Bandwidth: across processors, memory, disks and networks, bandwidth improved by far larger factors than latency did, and there are physical and architectural reasons this asymmetry keeps holding. Meanwhile, most of the last two decades of hardware progress has come from parallelism, from more cores and wider vectors and deeper pipelines. An interface is not a throughput problem. It is a chain of steps where each one has to finish before the next can start, and no amount of parallelism shortens a dependency chain.',
        'Look at what that chain used to be. On the Apple IIe: the keyboard is scanned, the CPU writes a byte into memory-mapped text RAM, and the video circuitry paints it on the next pass of the beam. A handful of steps, all synchronous, no scheduler, no compositor, no abstraction between the byte and the phosphor. Now count the modern path. USB polling interval, kernel input stack, window server, application event loop, the framework\'s synthetic event system, a state update, a reconciliation pass, layout, paint, upload to the GPU, composite, and finally the display\'s own refresh and pixel response. Every one of those layers is individually cheap and individually justified. The latency is the sum, and nobody is looking at the sum.',
        'Some of that sum is not smooth but stair-stepped, which makes it worse than the arithmetic suggests. Frames land on a fixed clock, so work that misses its deadline by a microsecond waits for the next one and costs a whole frame. Buffering strategies that protect against stutter do so by keeping finished frames in hand, which trades latency away to buy smoothness. So the difference between just-fast-enough and just-too-slow is not a matter of a few percent of perceived responsiveness. It is discrete, and it is why an optimisation that shaves a small amount can feel like it changed everything, and why a small regression can feel like a different application.',
        "The thresholds this is being measured against have not moved, because they belong to people rather than to machines. Jakob Nielsen's response-time limits, drawn from work going back to Robert Miller in the late sixties, still describe them: about a tenth of a second before an action stops feeling instantaneous, about a second before a user notices the delay and starts losing the thread, about ten seconds before their attention leaves entirely. Hardware got faster by staggering multiples. The bar did not move at all, which means every gain was available to be spent, and every gain was spent.",
        'Underneath the application layer, the memory hierarchy quietly enforces its own version of the same lesson. A hit in L1 costs a few cycles; a trip to main memory costs hundreds. Modern processors are extraordinarily fast on the condition that the data is where they expect it, and that condition is exactly what layers of abstraction erode. Boxed values, pointer chasing, allocation churn, objects scattered across the heap by an ownership model that made the code easier to reason about. A supposedly fast language operating on scattered data will lose to a supposedly slow one operating on a contiguous array, and the difference is not the language at all. It is how many times the processor sat waiting on RAM.',
        'The network multiplies all of this by round trips. Bandwidth to the average device has improved beyond recognition; round-trip time is bounded by distance, routing and the behaviour of congested links, and has improved far less. If an interaction needs three sequential requests, each waiting on the response before the next can be formed, the user waits three round trips no matter how fat the pipe is. Load a token, then fetch the user, then fetch their data, then render. On the developer\'s machine, sitting on a fast connection close to the server, that waterfall is nearly invisible. On a phone on a busy mobile network, it is the entire experience.',
        'Now the economics, which is the part that actually determines outcomes. Every improvement in hardware is a budget, and budgets get spent rather than banked. They were spent on things that were genuinely worth buying: memory safety, cross-platform delivery from one codebase, hot reload, component models that let a team of forty work on one product without breaking each other, shipping weekly instead of annually. Those are real goods, and anyone claiming otherwise has not maintained a large native application across three platforms. But the benefits are concentrated on the people making the software and the costs are spread thinly across everyone using it, and a cost structured that way is one nobody has an incentive to defend against.',
        'That is compounded by the fact that latency has no owner. Features have owners, and bugs have owners, and outages have owners. Latency is the accumulated residue of hundreds of individually reasonable decisions: fifteen milliseconds for a new analytics hook, thirty for a framework upgrade that fixed a class of bugs, twenty for an accessibility layer, ten for an experiment framework. Every one of them is defensible in review and none of them is worth blocking a release over. There is no meeting where a fifteen-millisecond regression gets rejected, so the ratchet only turns one way, and after two years the app is half a second slower and nobody can point to the commit.',
        'There is also a category of slowness that is entirely self-inflicted in the name of polish. Spinners that appear after a couple of hundred milliseconds and advertise a wait the user had not yet noticed. Skeleton screens that reserve the wrong space, so the content arrives and everything jumps. Transitions that gate interaction on a three-hundred-millisecond animation, so the software is deliberately slower than the hardware requires because it looks considered. Meanwhile the thing that genuinely helps perceived speed, which is immediate acknowledgement of the input, gets skipped. An interface that responds instantly and then takes a moment to complete feels faster than one that is quicker overall but silent at the start, because what people register is the gap between the action and the first sign that anything heard them.',
        'Measurement makes this worse in a specific and avoidable way. Performance work is usually validated on a fast machine, on a fast network, with a warm cache, by a person who already has the app open, and reported as a median. None of those conditions describe the interaction that is actually hurting anyone. The one that matters is the ninety-fifth percentile, cold, on mid-range hardware, on a congested connection, on the first load of the day. That is where the long main-thread tasks, the garbage collection pauses, the cold starts and the unlucky retries all live, and they are precisely the events an average is designed to hide.',
        'The remedies are unglamorous and mostly organisational rather than technical. Measure end to end, from the physical input to the pixel changing, because that is the number the user experiences and every intermediate metric can improve while it gets worse. Set a budget for it and treat a regression as a defect rather than a trade-off, so the ratchet has something to push against. Take work off the critical path, and when work cannot be removed, acknowledge the input before doing it. Collapse dependent round trips into one. And stop paying for smoothness with responsiveness, because users forgive a dropped frame far more readily than they forgive a keystroke that does not appear when they press it. The machine is not slow; the distance between the keypress and the pixel got longer, and nobody was assigned to keep it short.',
    ],
];
