<?php

namespace App\Support\Integrations;

use App\Models\Post;
use App\Support\HtmlSanitizer;
use ZipArchive;

/**
 * Manuscript formats: IEEE-style LaTeX, and DOCX.
 *
 * This is the honest half of "academic export". Direct submission to IEEE or
 * Springer is not possible — both accept manuscripts only through editorial
 * systems (ScholarOne, Editorial Manager, Snapp) that publish no third-party
 * submission API, and a button claiming otherwise would not work. What is real
 * is handing the author a file in the format the portal expects, which is the
 * step immediately before the portal anyway.
 */
class ManuscriptExporter
{
    /** IEEEtran — the class the conferences actually ask for. */
    public static function toLatex(Post $post): string
    {
        $title = self::escapeTex($post->title);
        $author = self::escapeTex($post->persona?->display_name ?? $post->user?->name ?? 'Anonymous');
        $abstract = self::escapeTex($post->excerpt ?? HtmlSanitizer::excerpt($post->body, 900));
        $date = $post->published_at?->format('j F Y') ?? '';
        $url = route('posts.show', $post);

        $lines = [
            '% Generated by '.config('app.name').'. Compile with pdflatex.',
            '% Source: '.$url,
            '',
            '\documentclass[conference]{IEEEtran}',
            '\IEEEoverridecommandlockouts',
            '',
            '\usepackage{cite}',
            '\usepackage{amsmath,amssymb,amsfonts}',
            '\usepackage{graphicx}',
            '\usepackage[utf8]{inputenc}',
            '\usepackage{url}',
            '',
            '\begin{document}',
            '',
            '\title{'.$title.'}',
            '',
            '\author{\IEEEauthorblockN{'.$author.'}',
            '\IEEEauthorblockA{\textit{'.self::escapeTex(config('app.name')).'} \\\\',
            '\url{'.$url.'}}}',
            '',
            '\maketitle',
            '',
            '\begin{abstract}',
            $abstract,
            '\end{abstract}',
            '',
            '\begin{IEEEkeywords}',
            self::escapeTex(self::keywords($post)),
            '\end{IEEEkeywords}',
            '',
            self::bodyToTex($post->body),
            '',
            '% Originally published '.self::escapeTex($date).'.',
            '\end{document}',
            '',
        ];

        return implode("\n", $lines);
    }

    /**
     * A minimal but valid DOCX.
     *
     * Built by hand rather than by pulling in a Word library: the document is a
     * title, headings and paragraphs, and the three-file OOXML skeleton needed
     * for that is smaller than the dependency would be.
     */
    public static function toDocx(Post $post): string
    {
        $file = tempnam(sys_get_temp_dir(), 'inkfathom-docx');
        $zip = new ZipArchive;

        // OVERWRITE because tempnam already created the (empty) file, and an
        // empty file is not a valid archive to open.
        $zip->open($file, ZipArchive::OVERWRITE);

        $zip->addFromString('[Content_Types].xml', self::contentTypes());
        $zip->addFromString('_rels/.rels', self::rels());
        $zip->addFromString('word/document.xml', self::documentXml($post));

        $zip->close();

        $contents = (string) file_get_contents($file);
        unlink($file);

        return $contents;
    }

    /* -------------------- LaTeX -------------------- */

    /**
     * Escape the characters TeX treats as syntax.
     *
     * Order matters: the backslash has to go first, or it would escape the
     * backslashes introduced by the later replacements.
     */
    private static function escapeTex(string $text): string
    {
        $text = str_replace('\\', '\textbackslash{}', $text);

        return str_replace(
            ['&', '%', '$', '#', '_', '{', '}', '~', '^'],
            ['\&', '\%', '\$', '\#', '\_', '\{', '\}', '\textasciitilde{}', '\textasciicircum{}'],
            $text,
        );
    }

    private static function bodyToTex(string $html): string
    {
        $out = [];

        // Only the sanitiser's allowlisted tags can appear, so this is a closed
        // set rather than a general HTML-to-TeX converter.
        $html = preg_replace('#<figure[^>]*>.*?</figure>#is', '', $html) ?? $html;

        preg_match_all('#<(h2|h3|h4|p|blockquote|pre)[^>]*>(.*?)</\1>#is', $html, $matches, PREG_SET_ORDER);

        foreach ($matches as [$_, $tag, $inner]) {
            $text = self::inlineToTex($inner);

            if ($text === '') {
                continue;
            }

            $out[] = match ($tag) {
                'h2' => "\n\\section{".$text.'}',
                'h3' => "\n\\subsection{".$text.'}',
                'h4' => "\n\\subsubsection{".$text.'}',
                'blockquote' => "\n\\begin{quote}\n".$text."\n\\end{quote}",
                'pre' => "\n\\begin{verbatim}\n".$text."\n\\end{verbatim}",
                default => "\n".$text,
            };
        }

        return implode("\n", $out);
    }

    /**
     * Inline HTML to TeX.
     *
     * Formatting is reduced to placeholders *before* escaping, not after.
     * Escaping first and then trying to un-escape the commands does not work:
     * escapeTex turns the braces of `\textbf{x}` into `\{x\}` too, and
     * unpicking that reliably is harder than not creating the problem. The
     * placeholders are plain letters and @ signs, none of which TeX treats as
     * syntax, so they pass through the escaper untouched.
     */
    private static function inlineToTex(string $html): string
    {
        $urls = [];

        $html = preg_replace_callback(
            '#<a[^>]*href="([^"]*)"[^>]*>(.*?)</a>#is',
            static function (array $match) use (&$urls): string {
                $urls[] = $match[1];

                return $match[2].'@@LINK'.(count($urls) - 1).'@@';
            },
            $html,
        ) ?? $html;

        $html = preg_replace('#<strong[^>]*>(.*?)</strong>#is', '@@BOLDA@@$1@@BOLDB@@', $html) ?? $html;
        $html = preg_replace('#<em[^>]*>(.*?)</em>#is', '@@ITALA@@$1@@ITALB@@', $html) ?? $html;

        $text = html_entity_decode(strip_tags($html), ENT_QUOTES | ENT_HTML5, 'UTF-8');
        $text = self::escapeTex($text);

        $text = str_replace(
            ['@@BOLDA@@', '@@BOLDB@@', '@@ITALA@@', '@@ITALB@@'],
            ['\textbf{', '}', '\textit{', '}'],
            $text,
        );

        foreach ($urls as $index => $url) {
            // \url{} takes the address verbatim, so it must not be escaped.
            $text = str_replace('@@LINK'.$index.'@@', '\footnote{\url{'.$url.'}}', $text);
        }

        return trim(preg_replace('/\s+/', ' ', $text) ?? $text);
    }

    private static function keywords(Post $post): string
    {
        $names = $post->relationLoaded('categories') ? $post->categories->pluck('name')->all() : [];

        if ($names === []) {
            $names = array_filter([$post->universe?->name]);
        }

        return implode(', ', $names) ?: 'writing';
    }

    /* -------------------- DOCX -------------------- */

    private static function contentTypes(): string
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            .'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            .'<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
            .'<Default Extension="xml" ContentType="application/xml"/>'
            .'<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
            .'</Types>';
    }

    private static function rels(): string
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            .'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            .'<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
            .'</Relationships>';
    }

    private static function documentXml(Post $post): string
    {
        $body = self::paragraph($post->title, 'Title');
        $body .= self::paragraph($post->persona?->display_name ?? $post->user?->name ?? '', 'Subtitle');

        $html = preg_replace('#<figure[^>]*>.*?</figure>#is', '', $post->body) ?? $post->body;

        preg_match_all('#<(h2|h3|h4|p|blockquote)[^>]*>(.*?)</\1>#is', $html, $matches, PREG_SET_ORDER);

        foreach ($matches as [$_, $tag, $inner]) {
            $text = trim(html_entity_decode(strip_tags($inner), ENT_QUOTES | ENT_HTML5, 'UTF-8'));

            if ($text === '') {
                continue;
            }

            $body .= self::paragraph($text, match ($tag) {
                'h2' => 'Heading1',
                'h3' => 'Heading2',
                'h4' => 'Heading3',
                'blockquote' => 'Quote',
                default => 'Normal',
            });
        }

        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            .'<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
            .'<w:body>'.$body.'</w:body>'
            .'</w:document>';
    }

    private static function paragraph(string $text, string $style): string
    {
        if ($text === '') {
            return '';
        }

        // xml:space="preserve" or Word eats leading and trailing spaces.
        return '<w:p><w:pPr><w:pStyle w:val="'.$style.'"/></w:pPr>'
            .'<w:r><w:t xml:space="preserve">'.htmlspecialchars($text, ENT_XML1 | ENT_QUOTES, 'UTF-8').'</w:t></w:r></w:p>';
    }
}
