<?php

namespace App\Support\Academic;

/**
 * IEEEtran manuscript source.
 *
 * The output compiles as-is against the standard IEEEtran class, which is the
 * only useful definition of correct here — a .tex file that needs hand-fixing
 * before it builds has not saved anyone anything.
 *
 * Escaping is the part that matters: LaTeX has ten special characters and
 * getting any of them wrong produces a file that fails to compile, usually
 * with an error pointing somewhere else entirely.
 */
class LatexExporter
{
    /** Backslash must be replaced first, or it re-escapes everything after it. */
    private const ESCAPES = [
        '\\' => '\textbackslash{}',
        '&' => '\&',
        '%' => '\%',
        '$' => '\$',
        '#' => '\#',
        '_' => '\_',
        '{' => '\{',
        '}' => '\}',
        '~' => '\textasciitilde{}',
        '^' => '\textasciicircum{}',
    ];

    public static function render(Manuscript $manuscript): string
    {
        $out = '% Generated by '.self::escape($manuscript->siteName)."\n";
        $out .= '% Source: '.self::escape($manuscript->url)."\n";
        $out .= "%\n% Compile with pdflatex; requires the IEEEtran class.\n\n";

        $out .= "\\documentclass[conference]{IEEEtran}\n";
        $out .= "\\IEEEoverrideCommandLockouts\n";
        $out .= "\\usepackage[T1]{fontenc}\n";
        $out .= "\\usepackage[utf8]{inputenc}\n";
        $out .= "\\usepackage{cite}\n";
        $out .= "\\usepackage{graphicx}\n";
        $out .= "\\usepackage{url}\n\n";

        $out .= "\\begin{document}\n\n";
        $out .= '\\title{'.self::escape($manuscript->title)."}\n\n";

        $out .= '\\author{\\IEEEauthorblockN{'.self::escape($manuscript->authorName)."}\n";
        $out .= '\\IEEEauthorblockA{'.self::escape($manuscript->affiliation ?? $manuscript->siteName);

        if ($manuscript->orcid) {
            $out .= "\\\\\nORCID: ".self::escape($manuscript->orcid);
        }

        $out .= "}}\n\n";
        $out .= "\\maketitle\n\n";

        if ($manuscript->abstract !== '') {
            $out .= "\\begin{abstract}\n".self::escape($manuscript->abstract)."\n\\end{abstract}\n\n";
        }

        if ($manuscript->keywords !== []) {
            $out .= "\\begin{IEEEkeywords}\n"
                .self::escape(implode(', ', $manuscript->keywords))
                ."\n\\end{IEEEkeywords}\n\n";
        }

        foreach (BlockParser::parse($manuscript->bodyHtml) as $block) {
            $out .= self::block($block);
        }

        $out .= "\\end{document}\n";

        return $out;
    }

    /** @param  array<string, mixed>  $block */
    private static function block(array $block): string
    {
        return match ($block['type']) {
            'heading' => match ($block['level']) {
                2 => '\\section{'.self::escape($block['text'])."}\n\n",
                3 => '\\subsection{'.self::escape($block['text'])."}\n\n",
                default => '\\subsubsection{'.self::escape($block['text'])."}\n\n",
            },
            'quote' => "\\begin{quote}\n".self::escape($block['text'])."\n\\end{quote}\n\n",
            // verbatim takes its content raw by definition — escaping it would
            // print the escapes.
            'code' => "\\begin{verbatim}\n".$block['text']."\n\\end{verbatim}\n\n",
            'bullets' => self::list('itemize', $block['items'] ?? []),
            'numbers' => self::list('enumerate', $block['items'] ?? []),
            'figure' => "\\begin{quote}\n\\textit{".self::escape($block['text'])."}\n\\end{quote}\n\n",
            default => self::escape($block['text'])."\n\n",
        };
    }

    /** @param  array<int, string>  $items */
    private static function list(string $environment, array $items): string
    {
        if ($items === []) {
            return '';
        }

        $out = "\\begin{{$environment}}\n";

        foreach ($items as $item) {
            $out .= '  \\item '.self::escape($item)."\n";
        }

        return $out."\\end{{$environment}}\n\n";
    }

    public static function escape(string $value): string
    {
        return str_replace(array_keys(self::ESCAPES), array_values(self::ESCAPES), $value);
    }
}
